name: Pandoc - markdown to pdf
run-name: pandoc python converter
on:
  workflow_dispatch:
    inputs:
      markdown-source-dir:
        description: markdown input directory
        required: true
        type: string
      upload-artifact:
        description: upload artifact
        required: false
        type: boolean

defaults:
  run:
    shell: sh
            
jobs:
  md-to-pdf:
    name: Pandoc - markdown to pdf
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:edge-ubuntu
      options: --cpus 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        run: |
           apt-get -q --no-allow-insecure-repositories update
      #    apk add python3 py3-pip
      #    python3 -m venv pandoc
      #    . pandoc/bin/activate
      #    pip install pypandoc

      #- name: Run pypandoc
      #  run: |
      #    python3 converter.py ${{ inputs.markdown-source-dir }}

      - name: Run pandoc
        run: |
          pandoc --help
          pandoc README.md --from markdown --to html -o README.html
          pandoc README.md --from markdown --to pdf -o README.pdf

      - name: Upload artifacts
        if: inputs.upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: pandoc-artifact
          path: |
            README.html
            README.pdf
            test/_output/
          retention-days: 3

