name: Pandoc - convert markdown to pdf
run-name: python converter
on:
  workflow_dispatch:
    inputs:
        markdown-source-dir:
          description: markdown input directory
          required: true
          type: string
            
jobs:
  md-to-pdf:
    name: Pandoc - MD to PDF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Pandoc core image
        uses: docker://pandoc/core:2.9
        with:
          args: "--help"

